name: Publish
on:
  push:
    branches:
      - main
    paths:
      - jsr.json

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: denoland/setup-deno@v1

      - uses: actions/checkout@v4

      - run: deno publish
